# ~/IOT/p3/git-repo/app/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil-playground
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
        - name: playground-container
          # Start with v1
          image: wil42/playground:v1
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: wil-playground-svc
spec:
  # Use LoadBalancer type - K3d's service LB will pick this up
  # and expose it via the port mapping we did with 'k3d cluster create'
  type: LoadBalancer
  selector:
    app: wil-playground
  ports:
    - protocol: TCP
      port: 8888 # Service port
      targetPort: 8888 # Container port
